openapi: 3.0.0
info:
  title: Hack as a Service API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development
security:
  - cookieAuth: []
  - bearerAuth: []

paths:
  /users/me:
    get:
      summary: Fetch the current user
      tags:
        - Users
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          description: Internal server error
        "401":
          description: Unauthorized
  /teams:
    post:
      summary: Create a team
      tags:
        - Teams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                avatar:
                  type: string
              required:
                - name
              example:
                name: Hack as a Service
                avatar: https://doggo.ninja/dzippy.png
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"
        "500":
          description: Internal server error
        "401":
          description: Unauthorized

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: haas_token
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        slack_user_id:
          type: string
        name:
          type: string
        avatar:
          type: string
      required:
        - id
        - slack_user_id
      example:
        id: 5
        slack_user_id: U0266FRGP
        name: Zach Latta
        avatar: https://ca.slack-edge.com/T0266FRGM-U0266FRGP-db89498acd5d-192
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        avatar:
          type: string
        personal:
          type: boolean
      required:
        - id
        - name
        - personal
      example:
        id: 8
        name: Hack as a Service
        avatar: https://doggo.ninja/dzippy.png
        personal: false
